name: Build Visual Novel Creator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Package application
      run: npm run package

    - name: Upload Windows build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: visual-novel-creator-win
        path: dist/VisualNovelCreator-win32-x64/**
        if-no-files-found: error